-- Visitor analytics for the staff dashboard.
--
-- One append-only table rather than a counter column per thing that can be
-- clicked: a counter answers "how many" but never "when" or "by how many
-- people", and every question staff have asked so far ("is this code getting
-- used?", "how long do people stay?") needs at least one of those. Aggregates
-- are computed at read time in src/lib/data/analytics.ts.
--
-- `creator_id`, not `profile_id`: an event is ABOUT a creator but generated by
-- a visitor, and the different name keeps that visible in every join. Cascades
-- with the profile so deleting a creator takes their history with them.
CREATE TYPE "public"."analytics_event_type" AS ENUM(
  'profile_view',
  'promo_click',
  'promo_used',
  'link_click',
  'session_duration'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "analytics_events" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "creator_id" uuid NOT NULL REFERENCES "profile"("id") ON DELETE CASCADE,
  -- The signed-in viewer's auth user id, or a random per-browser id. Never an
  -- IP, hashed or otherwise — same line ask_message draws.
  "viewer_session_id" uuid,
  "event_type" "analytics_event_type" NOT NULL,
  "metadata" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
-- Every dashboard read is "this creator, this event type, over time".
CREATE INDEX IF NOT EXISTS "analytics_events_creator_type_created_idx"
  ON "analytics_events" ("creator_id", "event_type", "created_at");
